server:
  port: 8080
  servlet:
    context-path: /gpms    #项目访问路径
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

spring:
  profiles:
    active: prod
  banner:
    location: /banner.txt



